id: P000387
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:20.112991
source_metadata:
  id: bdr:W1KG16609
  title: སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱི་སྐྱེས་རབས་བརྒྱ་པ།
  author: ''
  volumes:
    0163df03090e4382861e2421d0c47429:
      image_group_id: I1KG16644
      title: Volume 1 of sangs rgyas bcos ldan 'das kyi skyes rabs brgya pa/
      volume_number: 1
      total_pages: 752
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
